VERSION 0.8

ARG core=github.com/formancehq/earthly

IMPORT $core AS core
IMPORT ../.. AS stack
IMPORT .. AS ee

FROM core+base-image

sources:
    WORKDIR src
    DO stack+INCLUDE_GO_LIBS --LOCATION libs/go-libs
    WORKDIR /src/ee/auth
    COPY go.* .
    COPY --dir cmd pkg .
    COPY main.go .
    SAVE ARTIFACT /src

compile:
    FROM core+builder-image
    COPY (+sources/*) /src
    WORKDIR /src/ee/auth
    ARG VERSION=latest
    DO core+GO_COMPILE --VERSION=$VERSION

build-image:
    FROM core+final-image
    ENTRYPOINT ["/bin/auth"]
    CMD ["serve"]
    COPY (+compile/main) /bin/auth
    ARG REPOSITORY=ghcr.io
    ARG tag=latest
    DO core+SAVE_IMAGE --COMPONENT=auth --REPOSITORY=${REPOSITORY} --TAG=$tag

tests:
    FROM core+builder-image
    COPY (+sources/*) /src
    WORKDIR /src/ee/auth
    WITH DOCKER --pull=postgres:15-alpine
        DO core+GO_TESTS
    END

lint:
    FROM core+builder-image
    COPY (+sources/*) /src
    COPY +tidy/go.* .
    WORKDIR /src/ee/auth
    DO stack+GO_LINT
    SAVE ARTIFACT cmd AS LOCAL cmd
    SAVE ARTIFACT pkg AS LOCAL pkg
    SAVE ARTIFACT main.go AS LOCAL main.go

deploy:
    COPY (+sources/*) /src
    LET tag=$(tar cf - /src | sha1sum | awk '{print $1}')
    WAIT
        BUILD +build-image --tag=$tag
    END
    FROM core+vcluster-deployer-image
    RUN kubectl patch Versions.formance.com default -p "{\"spec\":{\"auth\": \"${tag}\"}}" --type=merge

deploy-staging:
    BUILD stack+deployer-module --MODULE=auth

pre-commit:
    WAIT
        BUILD +tidy
    END
    BUILD +lint

openapi:
    COPY ./openapi.yaml .
    SAVE ARTIFACT ./openapi.yaml

tidy:
    FROM core+builder-image
    COPY (+sources/src) /src
    WORKDIR /src/ee/auth
    DO stack+GO_TIDY

release:
    BUILD stack+goreleaser --path=ee/auth