<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Shared;


/**
 * ListTriggersResponse - List of triggers
 * 
 * @package formance\stack\Models\Shared
 * @access public
 */
class ListTriggersResponse
{
    /**
     * $data
     * 
     * @var array<\formance\stack\Models\Shared\Trigger> $data
     */
	#[\JMS\Serializer\Annotation\SerializedName('data')]
    #[\JMS\Serializer\Annotation\Type('array<formance\stack\Models\Shared\Trigger>')]
    public array $data;
    
	public function __construct()
	{
		$this->data = [];
	}
}
