<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Shared;


enum MigrationInfoState: string
{
    case ToDo = 'to do';
    case Done = 'done';
}
