<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\stack\Models\Shared;


class PaymentsAccount
{
	#[\JMS\Serializer\Annotation\SerializedName('accountName')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $accountName;
    
	#[\JMS\Serializer\Annotation\SerializedName('createdAt')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $createdAt;
    
	#[\JMS\Serializer\Annotation\SerializedName('defaultAsset')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $defaultAsset;
    
	#[\JMS\Serializer\Annotation\SerializedName('defaultCurrency')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $defaultCurrency;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $id;
    
	#[\JMS\Serializer\Annotation\SerializedName('provider')]
    #[\JMS\Serializer\Annotation\Type('enum<formance\stack\Models\Shared\Connector>')]
    public Connector $provider;
    
    /**
     * $raw
     * 
     * @var array<string, mixed> $raw
     */
	#[\JMS\Serializer\Annotation\SerializedName('raw')]
    #[\JMS\Serializer\Annotation\Type('array<string, mixed>')]
    public array $raw;
    
	#[\JMS\Serializer\Annotation\SerializedName('reference')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $reference;
    
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $type;
    
	public function __construct()
	{
		$this->accountName = "";
		$this->createdAt = new \DateTime();
		$this->defaultAsset = "";
		$this->defaultCurrency = "";
		$this->id = "";
		$this->provider = \formance\stack\Models\Shared\Connector::STRIPE;
		$this->raw = [];
		$this->reference = "";
		$this->type = "";
	}
}
