VERSION 0.8

ARG core=github.com/formancehq/earthly:v0.11.1
IMPORT $core AS core
IMPORT ../.. AS stack

FROM core+base-image

go-sources:
    COPY events.go go.* base.yaml /src/
    COPY --dir services /src/
    WORKDIR /src
    SAVE ARTIFACT /src

tidy:
    FROM core+builder-image
    COPY (+go-sources/*) /src
    WORKDIR /src
    DO stack+GO_TIDY
    SAVE ARTIFACT go.* AS LOCAL ./

lint:
    FROM core+builder-image
    COPY (+go-sources/*) /src
    WORKDIR /src
    COPY +tidy/go.* .
    DO stack+GO_LINT
    SAVE ARTIFACT * AS LOCAL ./

generate:
    RUN apk add nodejs npm
    WORKDIR /src
    COPY package* .
    RUN npm install
    RUN mkdir generated
    COPY index.js base.yaml .
    COPY --dir services .
    RUN node index.js
    SAVE ARTIFACT generated AS LOCAL ./generated

pre-commit:
    WAIT
      BUILD +tidy
    END
    BUILD +lint
    BUILD +generate