/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class ReadTriggerRequest extends SpeakeasyBase {
  /**
   * The trigger id
   */
  @SpeakeasyMetadata({
    data: "pathParam, style=simple;explode=false;name=triggerID",
  })
  triggerID: string;
}

export class ReadTriggerResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  /**
   * General error
   */
  @SpeakeasyMetadata()
  error?: shared.ErrorT;

  /**
   * A specific trigger
   */
  @SpeakeasyMetadata()
  readTriggerResponse?: shared.ReadTriggerResponse;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;
}
