VERSION 0.8
PROJECT FormanceHQ/wallets

IMPORT github.com/formancehq/earthly:feat/monorepo AS core
IMPORT ./../../components/ledger AS ledger

FROM core+base-image

sources:
    WORKDIR src
    DO core+INCLUDE_CORE_LIBS --LOCATION libs/core
    DO core+INCLURE_SDK_GO --LOCATION /src/releases/sdks/go
    WORKDIR /src/ee/wallets
    COPY go.* .
    COPY --dir pkg cmd .
    COPY main.go .
    SAVE ARTIFACT /src
    SAVE ARTIFACT /src/libs AS LOCAL ./libs

compile:
    FROM core+builder-image
    COPY (+sources/*) /src
    WORKDIR /src/ee/wallets
    ARG VERSION=latest
    DO --pass-args core+GO_COMPILE --VERSION=$VERSION

build-image:
    FROM core+final-image
    ENTRYPOINT ["/bin/wallets"]
    CMD ["serve"]
    COPY (+compile/main) /bin/wallets
    ARG REPOSITORY=ghcr.io
    ARG tag=latest
    DO core+SAVE_IMAGE --COMPONENT=wallets --REPOSITORY=${REPOSITORY} --TAG=$tag

tests:
    FROM core+builder-image
    COPY (+sources/*) /src
    WORKDIR /src/ee/wallets
    WITH DOCKER --pull=postgres:15-alpine
        DO --pass-args core+GO_TESTS
    END

deploy:
    COPY (+sources/*) /src
    LET tag=$(tar cf - /src | sha1sum | awk '{print $1}')
    WAIT
        BUILD --pass-args +build-image --tag=$tag
    END
    FROM --pass-args core+vcluster-deployer-image
    RUN kubectl patch Versions.formance.com default -p "{\"spec\":{\"wallets\": \"${tag}\"}}" --type=merge

deploy-staging:
    BUILD --pass-args core+deployer-module --MODULE=wallets

lint:
    FROM core+builder-image
    COPY (+sources/*) /src
    COPY --pass-args +tidy/go.* .
    WORKDIR /src/ee/wallets
    DO --pass-args core+GO_LINT
    SAVE ARTIFACT cmd AS LOCAL cmd
    SAVE ARTIFACT pkg AS LOCAL pkg
    SAVE ARTIFACT main.go AS LOCAL main.go

pre-commit:
    WAIT
      BUILD --pass-args +tidy
    END
    BUILD --pass-args +lint

openapi:
    DO --pass-args core+OPENAPI

tidy:
    FROM core+builder-image
    COPY --pass-args (+sources/src) /src
    WORKDIR /src/ee/wallets
    DO --pass-args core+GO_TIDY

release:
    FROM core+builder-image
    ARG mode=local
    COPY . /src
    DO core+GORELEASER --mode=$mode