VERSION 0.8

IMPORT github.com/formancehq/earthly:tags/v0.14.0 AS core
IMPORT ../../../.. AS stack
IMPORT ../../.. AS components

FROM core+base-image

sources:
    FROM core+builder-image
    WORKDIR /src
    COPY (stack+sources/out --LOCATION=libs/go-libs) libs/go-libs
    COPY (stack+sources/out --LOCATION=components/operator) components/operator
    WORKDIR /src/components/operator/tools/kubectl-stacks
    COPY go.* *.go .
    SAVE ARTIFACT /src

tidy:
    FROM core+builder-image
    COPY --pass-args (+sources/src) /src
    WORKDIR /src/components/operator/tools/kubectl-stacks
    DO --pass-args stack+GO_TIDY