VERSION 0.8

IMPORT github.com/formancehq/earthly:feat/monorepo AS core
IMPORT ../../ AS operator

FROM core+base-image

sources:
    FROM core+builder-image
    WORKDIR /src
    COPY (operator+sources/src/components/operator) /src/components/operator
    WORKDIR /src/components/operator/tools/kubectl-stacks
    COPY go.* *.go .
    SAVE ARTIFACT /src

tidy:
    FROM core+builder-image
    COPY --pass-args (+sources/src) /src
    WORKDIR /src/components/operator/tools/kubectl-stacks
    DO --pass-args core+GO_TIDY