// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CurrencyCloudConfig struct {
	APIKey string `json:"apiKey"`
	// The endpoint to use for the API. Defaults to https://devapi.currencycloud.com
	Endpoint *string `json:"endpoint,omitempty"`
	// Username of the API Key holder
	LoginID string `json:"loginID"`
	// The frequency at which the connector will fetch transactions
	PollingPeriod *string `json:"pollingPeriod,omitempty"`
}

func (o *CurrencyCloudConfig) GetAPIKey() string {
	if o == nil {
		return ""
	}
	return o.APIKey
}

func (o *CurrencyCloudConfig) GetEndpoint() *string {
	if o == nil {
		return nil
	}
	return o.Endpoint
}

func (o *CurrencyCloudConfig) GetLoginID() string {
	if o == nil {
		return ""
	}
	return o.LoginID
}

func (o *CurrencyCloudConfig) GetPollingPeriod() *string {
	if o == nil {
		return nil
	}
	return o.PollingPeriod
}
