// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// RunWorkflowResponse - The workflow instance
type RunWorkflowResponse struct {
	Data WorkflowInstance `json:"data"`
}
