// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type StageStatus struct {
	Error        *string    `json:"error,omitempty"`
	InstanceID   string     `json:"instanceID"`
	Stage        float64    `json:"stage"`
	StartedAt    time.Time  `json:"startedAt"`
	TerminatedAt *time.Time `json:"terminatedAt,omitempty"`
}
