// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type TriggerData struct {
	Event      string                 `json:"event"`
	Filter     *string                `json:"filter,omitempty"`
	Vars       map[string]interface{} `json:"vars,omitempty"`
	WorkflowID string                 `json:"workflowID"`
}
