// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type WorkflowInstanceHistoryStageOutput struct {
	CreateTransaction *ActivityCreateTransactionOutput `json:"CreateTransaction,omitempty"`
	DebitWallet       *ActivityDebitWalletOutput       `json:"DebitWallet,omitempty"`
	GetAccount        *ActivityGetAccountOutput        `json:"GetAccount,omitempty"`
	GetPayment        *ActivityGetPaymentOutput        `json:"GetPayment,omitempty"`
	GetWallet         *ActivityGetWalletOutput         `json:"GetWallet,omitempty"`
	RevertTransaction *ActivityRevertTransactionOutput `json:"RevertTransaction,omitempty"`
}
