// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/pkg/models/shared"
	"net/http"
)

type GetBalanceRequest struct {
	BalanceName string `pathParam:"style=simple,explode=false,name=balanceName"`
	ID          string `pathParam:"style=simple,explode=false,name=id"`
}

type GetBalanceResponse struct {
	ContentType string
	// Balance summary
	GetBalanceResponse *shared.GetBalanceResponse
	StatusCode         int
	RawResponse        *http.Response
	// Error
	WalletsErrorResponse *shared.WalletsErrorResponse
}
