// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/pkg/models/shared"
	"net/http"
)

type GetPaymentRequest struct {
	// The payment ID.
	PaymentID string `pathParam:"style=simple,explode=false,name=paymentId"`
}

type GetPaymentResponse struct {
	ContentType string
	// OK
	PaymentResponse *shared.PaymentResponse
	StatusCode      int
	RawResponse     *http.Response
}
