/*
Formance Simple ingester Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ingesterclient

import (
	"encoding/json"
)

// checks if the ListPipelines200ResponseCursor type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListPipelines200ResponseCursor{}

// ListPipelines200ResponseCursor struct for ListPipelines200ResponseCursor
type ListPipelines200ResponseCursor struct {
	PageSize int64 `json:"pageSize"`
	HasMore bool `json:"hasMore"`
	Previous *string `json:"previous,omitempty"`
	Next *string `json:"next,omitempty"`
	Data []Pipeline `json:"data,omitempty"`
}

// NewListPipelines200ResponseCursor instantiates a new ListPipelines200ResponseCursor object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListPipelines200ResponseCursor(pageSize int64, hasMore bool) *ListPipelines200ResponseCursor {
	this := ListPipelines200ResponseCursor{}
	this.PageSize = pageSize
	this.HasMore = hasMore
	return &this
}

// NewListPipelines200ResponseCursorWithDefaults instantiates a new ListPipelines200ResponseCursor object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListPipelines200ResponseCursorWithDefaults() *ListPipelines200ResponseCursor {
	this := ListPipelines200ResponseCursor{}
	return &this
}

// GetPageSize returns the PageSize field value
func (o *ListPipelines200ResponseCursor) GetPageSize() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value
// and a boolean to check if the value has been set.
func (o *ListPipelines200ResponseCursor) GetPageSizeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PageSize, true
}

// SetPageSize sets field value
func (o *ListPipelines200ResponseCursor) SetPageSize(v int64) {
	o.PageSize = v
}

// GetHasMore returns the HasMore field value
func (o *ListPipelines200ResponseCursor) GetHasMore() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value
// and a boolean to check if the value has been set.
func (o *ListPipelines200ResponseCursor) GetHasMoreOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasMore, true
}

// SetHasMore sets field value
func (o *ListPipelines200ResponseCursor) SetHasMore(v bool) {
	o.HasMore = v
}

// GetPrevious returns the Previous field value if set, zero value otherwise.
func (o *ListPipelines200ResponseCursor) GetPrevious() string {
	if o == nil || IsNil(o.Previous) {
		var ret string
		return ret
	}
	return *o.Previous
}

// GetPreviousOk returns a tuple with the Previous field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListPipelines200ResponseCursor) GetPreviousOk() (*string, bool) {
	if o == nil || IsNil(o.Previous) {
		return nil, false
	}
	return o.Previous, true
}

// HasPrevious returns a boolean if a field has been set.
func (o *ListPipelines200ResponseCursor) HasPrevious() bool {
	if o != nil && !IsNil(o.Previous) {
		return true
	}

	return false
}

// SetPrevious gets a reference to the given string and assigns it to the Previous field.
func (o *ListPipelines200ResponseCursor) SetPrevious(v string) {
	o.Previous = &v
}

// GetNext returns the Next field value if set, zero value otherwise.
func (o *ListPipelines200ResponseCursor) GetNext() string {
	if o == nil || IsNil(o.Next) {
		var ret string
		return ret
	}
	return *o.Next
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListPipelines200ResponseCursor) GetNextOk() (*string, bool) {
	if o == nil || IsNil(o.Next) {
		return nil, false
	}
	return o.Next, true
}

// HasNext returns a boolean if a field has been set.
func (o *ListPipelines200ResponseCursor) HasNext() bool {
	if o != nil && !IsNil(o.Next) {
		return true
	}

	return false
}

// SetNext gets a reference to the given string and assigns it to the Next field.
func (o *ListPipelines200ResponseCursor) SetNext(v string) {
	o.Next = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ListPipelines200ResponseCursor) GetData() []Pipeline {
	if o == nil || IsNil(o.Data) {
		var ret []Pipeline
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListPipelines200ResponseCursor) GetDataOk() ([]Pipeline, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ListPipelines200ResponseCursor) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []Pipeline and assigns it to the Data field.
func (o *ListPipelines200ResponseCursor) SetData(v []Pipeline) {
	o.Data = v
}

func (o ListPipelines200ResponseCursor) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListPipelines200ResponseCursor) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["pageSize"] = o.PageSize
	toSerialize["hasMore"] = o.HasMore
	if !IsNil(o.Previous) {
		toSerialize["previous"] = o.Previous
	}
	if !IsNil(o.Next) {
		toSerialize["next"] = o.Next
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableListPipelines200ResponseCursor struct {
	value *ListPipelines200ResponseCursor
	isSet bool
}

func (v NullableListPipelines200ResponseCursor) Get() *ListPipelines200ResponseCursor {
	return v.value
}

func (v *NullableListPipelines200ResponseCursor) Set(val *ListPipelines200ResponseCursor) {
	v.value = val
	v.isSet = true
}

func (v NullableListPipelines200ResponseCursor) IsSet() bool {
	return v.isSet
}

func (v *NullableListPipelines200ResponseCursor) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListPipelines200ResponseCursor(val *ListPipelines200ResponseCursor) *NullableListPipelines200ResponseCursor {
	return &NullableListPipelines200ResponseCursor{value: val, isSet: true}
}

func (v NullableListPipelines200ResponseCursor) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListPipelines200ResponseCursor) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


