// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ConfigUser struct {
	Endpoint   string   `json:"endpoint"`
	EventTypes []string `json:"eventTypes"`
	Name       *string  `json:"name,omitempty"`
	Secret     *string  `json:"secret,omitempty"`
}

func (o *ConfigUser) GetEndpoint() string {
	if o == nil {
		return ""
	}
	return o.Endpoint
}

func (o *ConfigUser) GetEventTypes() []string {
	if o == nil {
		return []string{}
	}
	return o.EventTypes
}

func (o *ConfigUser) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *ConfigUser) GetSecret() *string {
	if o == nil {
		return nil
	}
	return o.Secret
}
