// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ConnectorResponseData struct {
	ConnectorID string `json:"connectorID"`
}

func (o *ConnectorResponseData) GetConnectorID() string {
	if o == nil {
		return ""
	}
	return o.ConnectorID
}

type ConnectorResponse struct {
	Data ConnectorResponseData `json:"data"`
}

func (o *ConnectorResponse) GetData() ConnectorResponseData {
	if o == nil {
		return ConnectorResponseData{}
	}
	return o.Data
}
