// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PolicyRequest struct {
	LedgerName     string         `json:"ledgerName"`
	LedgerQuery    map[string]any `json:"ledgerQuery"`
	Name           string         `json:"name"`
	PaymentsPoolID string         `json:"paymentsPoolID"`
}

func (o *PolicyRequest) GetLedgerName() string {
	if o == nil {
		return ""
	}
	return o.LedgerName
}

func (o *PolicyRequest) GetLedgerQuery() map[string]any {
	if o == nil {
		return map[string]any{}
	}
	return o.LedgerQuery
}

func (o *PolicyRequest) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *PolicyRequest) GetPaymentsPoolID() string {
	if o == nil {
		return ""
	}
	return o.PaymentsPoolID
}
