// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type V2StageSendSourceWallet struct {
	Balance *string `json:"balance,omitempty"`
	ID      string  `json:"id"`
}

func (o *V2StageSendSourceWallet) GetBalance() *string {
	if o == nil {
		return nil
	}
	return o.Balance
}

func (o *V2StageSendSourceWallet) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}
