// Code generated by go-swagger; DO NOT EDIT.

package expected_transactions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostV1betaExpectedTransactionsIDArchiveParams creates a new PostV1betaExpectedTransactionsIDArchiveParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostV1betaExpectedTransactionsIDArchiveParams() *PostV1betaExpectedTransactionsIDArchiveParams {
	return &PostV1betaExpectedTransactionsIDArchiveParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostV1betaExpectedTransactionsIDArchiveParamsWithTimeout creates a new PostV1betaExpectedTransactionsIDArchiveParams object
// with the ability to set a timeout on a request.
func NewPostV1betaExpectedTransactionsIDArchiveParamsWithTimeout(timeout time.Duration) *PostV1betaExpectedTransactionsIDArchiveParams {
	return &PostV1betaExpectedTransactionsIDArchiveParams{
		timeout: timeout,
	}
}

// NewPostV1betaExpectedTransactionsIDArchiveParamsWithContext creates a new PostV1betaExpectedTransactionsIDArchiveParams object
// with the ability to set a context for a request.
func NewPostV1betaExpectedTransactionsIDArchiveParamsWithContext(ctx context.Context) *PostV1betaExpectedTransactionsIDArchiveParams {
	return &PostV1betaExpectedTransactionsIDArchiveParams{
		Context: ctx,
	}
}

// NewPostV1betaExpectedTransactionsIDArchiveParamsWithHTTPClient creates a new PostV1betaExpectedTransactionsIDArchiveParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostV1betaExpectedTransactionsIDArchiveParamsWithHTTPClient(client *http.Client) *PostV1betaExpectedTransactionsIDArchiveParams {
	return &PostV1betaExpectedTransactionsIDArchiveParams{
		HTTPClient: client,
	}
}

/*
PostV1betaExpectedTransactionsIDArchiveParams contains all the parameters to send to the API endpoint

	for the post v1beta expected transactions ID archive operation.

	Typically these are written to a http.Request.
*/
type PostV1betaExpectedTransactionsIDArchiveParams struct {

	/* ID.

	   Expected Transaction ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post v1beta expected transactions ID archive params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostV1betaExpectedTransactionsIDArchiveParams) WithDefaults() *PostV1betaExpectedTransactionsIDArchiveParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post v1beta expected transactions ID archive params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostV1betaExpectedTransactionsIDArchiveParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post v1beta expected transactions ID archive params
func (o *PostV1betaExpectedTransactionsIDArchiveParams) WithTimeout(timeout time.Duration) *PostV1betaExpectedTransactionsIDArchiveParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post v1beta expected transactions ID archive params
func (o *PostV1betaExpectedTransactionsIDArchiveParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post v1beta expected transactions ID archive params
func (o *PostV1betaExpectedTransactionsIDArchiveParams) WithContext(ctx context.Context) *PostV1betaExpectedTransactionsIDArchiveParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post v1beta expected transactions ID archive params
func (o *PostV1betaExpectedTransactionsIDArchiveParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post v1beta expected transactions ID archive params
func (o *PostV1betaExpectedTransactionsIDArchiveParams) WithHTTPClient(client *http.Client) *PostV1betaExpectedTransactionsIDArchiveParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post v1beta expected transactions ID archive params
func (o *PostV1betaExpectedTransactionsIDArchiveParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the post v1beta expected transactions ID archive params
func (o *PostV1betaExpectedTransactionsIDArchiveParams) WithID(id string) *PostV1betaExpectedTransactionsIDArchiveParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the post v1beta expected transactions ID archive params
func (o *PostV1betaExpectedTransactionsIDArchiveParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PostV1betaExpectedTransactionsIDArchiveParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
