// Code generated by go-swagger; DO NOT EDIT.

package expected_transactions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/formancehq/payments/cmd/connectors/internal/connectors/atlar/models"
)

// PostV1betaExpectedTransactionsIDReconcileReader is a Reader for the PostV1betaExpectedTransactionsIDReconcile structure.
type PostV1betaExpectedTransactionsIDReconcileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostV1betaExpectedTransactionsIDReconcileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostV1betaExpectedTransactionsIDReconcileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /v1beta/expected-transactions/{id}:reconcile] PostV1betaExpectedTransactionsIDReconcile", response, response.Code())
	}
}

// NewPostV1betaExpectedTransactionsIDReconcileOK creates a PostV1betaExpectedTransactionsIDReconcileOK with default headers values
func NewPostV1betaExpectedTransactionsIDReconcileOK() *PostV1betaExpectedTransactionsIDReconcileOK {
	return &PostV1betaExpectedTransactionsIDReconcileOK{}
}

/*
PostV1betaExpectedTransactionsIDReconcileOK describes a response with status code 200, with default header values.

The Expected Transaction
*/
type PostV1betaExpectedTransactionsIDReconcileOK struct {
	Payload *models.ExpectedTransaction
}

// IsSuccess returns true when this post v1beta expected transactions Id reconcile o k response has a 2xx status code
func (o *PostV1betaExpectedTransactionsIDReconcileOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post v1beta expected transactions Id reconcile o k response has a 3xx status code
func (o *PostV1betaExpectedTransactionsIDReconcileOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post v1beta expected transactions Id reconcile o k response has a 4xx status code
func (o *PostV1betaExpectedTransactionsIDReconcileOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post v1beta expected transactions Id reconcile o k response has a 5xx status code
func (o *PostV1betaExpectedTransactionsIDReconcileOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post v1beta expected transactions Id reconcile o k response a status code equal to that given
func (o *PostV1betaExpectedTransactionsIDReconcileOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post v1beta expected transactions Id reconcile o k response
func (o *PostV1betaExpectedTransactionsIDReconcileOK) Code() int {
	return 200
}

func (o *PostV1betaExpectedTransactionsIDReconcileOK) Error() string {
	return fmt.Sprintf("[POST /v1beta/expected-transactions/{id}:reconcile][%d] postV1betaExpectedTransactionsIdReconcileOK  %+v", 200, o.Payload)
}

func (o *PostV1betaExpectedTransactionsIDReconcileOK) String() string {
	return fmt.Sprintf("[POST /v1beta/expected-transactions/{id}:reconcile][%d] postV1betaExpectedTransactionsIdReconcileOK  %+v", 200, o.Payload)
}

func (o *PostV1betaExpectedTransactionsIDReconcileOK) GetPayload() *models.ExpectedTransaction {
	return o.Payload
}

func (o *PostV1betaExpectedTransactionsIDReconcileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ExpectedTransaction)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
