VERSION --arg-scope-and-set --pass-args --use-function-keyword 0.7

ARG core=github.com/formancehq/earthly
IMPORT $core AS core
IMPORT ../.. AS stack

sources:
  FROM core+base-image
  WORKDIR /src
  COPY Chart.lock /src/Chart.lock
  COPY Chart.yaml /src/Chart.yaml
  COPY README.md /src/README.md
  COPY values.yaml /src/values.yaml
  COPY --dir templates /src/templates
  SAVE ARTIFACT /src

replace-v2-values:
  FROM core+base-image
  RUN apk add yq jq
  COPY values.yaml .
  
  ARG --required TAG
  LET SERVICES = $(yq eval -o=j '.versions.files."v2.0" | keys' ./values.yaml | jq -c '.[]')
  FOR SERVICE IN $SERVICES
    RUN yq -i '.versions.files."v2.0".'$SERVICE=\"$TAG\" ./values.yaml
  END

  SAVE ARTIFACT ./values.yaml AS LOCAL values.yaml

helm-validate:
  FROM core+helm-base
  WORKDIR /src
  COPY (stack+sources/out --LOCATION=ee/agent/helm) /src/ee/agent/helm
  COPY (stack+sources/out --LOCATION=components/operator/helm) /src/components/operator/helm
  COPY (+sources/src) /src/helm/regions
  WORKDIR /src/helm/regions
  RUN helm dependencies update
  RUN helm dependencies build
  DO --pass-args core+HELM_VALIDATE
  SAVE ARTIFACT /src/helm
  SAVE ARTIFACT /src/helm/regions/Chart.lock AS LOCAL Chart.lock

helm-package:
  FROM core+helm-base
  WORKDIR /src
  COPY (+helm-validate/) /src
  WORKDIR /src/helm/regions
  RUN helm package .
  SAVE ARTIFACT /src/helm/regions/regions-*.tgz

helm-publish:
  FROM core+helm-base
  WORKDIR /src
  COPY (+helm-package/) /src
  WITH DOCKER
      RUN --secret GITHUB_TOKEN echo $GITHUB_TOKEN | docker login ghcr.io -u NumaryBot --password-stdin
  END
  WITH DOCKER
    RUN helm push /src/*.tgz oci://ghcr.io/formancehq/helm
  END