// Code generated by go-swagger; DO NOT EDIT.

package external_accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/formancehq/payments/cmd/connectors/internal/connectors/atlar/models"
)

// GetV1ExternalAccountsIDReader is a Reader for the GetV1ExternalAccountsID structure.
type GetV1ExternalAccountsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetV1ExternalAccountsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetV1ExternalAccountsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetV1ExternalAccountsIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /v1/external-accounts/{id}] GetV1ExternalAccountsID", response, response.Code())
	}
}

// NewGetV1ExternalAccountsIDOK creates a GetV1ExternalAccountsIDOK with default headers values
func NewGetV1ExternalAccountsIDOK() *GetV1ExternalAccountsIDOK {
	return &GetV1ExternalAccountsIDOK{}
}

/*
GetV1ExternalAccountsIDOK describes a response with status code 200, with default header values.

The identified external account
*/
type GetV1ExternalAccountsIDOK struct {
	Payload *models.ExternalAccount
}

// IsSuccess returns true when this get v1 external accounts Id o k response has a 2xx status code
func (o *GetV1ExternalAccountsIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get v1 external accounts Id o k response has a 3xx status code
func (o *GetV1ExternalAccountsIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 external accounts Id o k response has a 4xx status code
func (o *GetV1ExternalAccountsIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get v1 external accounts Id o k response has a 5xx status code
func (o *GetV1ExternalAccountsIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get v1 external accounts Id o k response a status code equal to that given
func (o *GetV1ExternalAccountsIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get v1 external accounts Id o k response
func (o *GetV1ExternalAccountsIDOK) Code() int {
	return 200
}

func (o *GetV1ExternalAccountsIDOK) Error() string {
	return fmt.Sprintf("[GET /v1/external-accounts/{id}][%d] getV1ExternalAccountsIdOK  %+v", 200, o.Payload)
}

func (o *GetV1ExternalAccountsIDOK) String() string {
	return fmt.Sprintf("[GET /v1/external-accounts/{id}][%d] getV1ExternalAccountsIdOK  %+v", 200, o.Payload)
}

func (o *GetV1ExternalAccountsIDOK) GetPayload() *models.ExternalAccount {
	return o.Payload
}

func (o *GetV1ExternalAccountsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ExternalAccount)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetV1ExternalAccountsIDNotFound creates a GetV1ExternalAccountsIDNotFound with default headers values
func NewGetV1ExternalAccountsIDNotFound() *GetV1ExternalAccountsIDNotFound {
	return &GetV1ExternalAccountsIDNotFound{}
}

/*
GetV1ExternalAccountsIDNotFound describes a response with status code 404, with default header values.

The identified external account doesn't exist
*/
type GetV1ExternalAccountsIDNotFound struct {
	Payload string
}

// IsSuccess returns true when this get v1 external accounts Id not found response has a 2xx status code
func (o *GetV1ExternalAccountsIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get v1 external accounts Id not found response has a 3xx status code
func (o *GetV1ExternalAccountsIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 external accounts Id not found response has a 4xx status code
func (o *GetV1ExternalAccountsIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get v1 external accounts Id not found response has a 5xx status code
func (o *GetV1ExternalAccountsIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get v1 external accounts Id not found response a status code equal to that given
func (o *GetV1ExternalAccountsIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get v1 external accounts Id not found response
func (o *GetV1ExternalAccountsIDNotFound) Code() int {
	return 404
}

func (o *GetV1ExternalAccountsIDNotFound) Error() string {
	return fmt.Sprintf("[GET /v1/external-accounts/{id}][%d] getV1ExternalAccountsIdNotFound  %+v", 404, o.Payload)
}

func (o *GetV1ExternalAccountsIDNotFound) String() string {
	return fmt.Sprintf("[GET /v1/external-accounts/{id}][%d] getV1ExternalAccountsIdNotFound  %+v", 404, o.Payload)
}

func (o *GetV1ExternalAccountsIDNotFound) GetPayload() string {
	return o.Payload
}

func (o *GetV1ExternalAccountsIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
