VERSION 0.8

ARG core=github.com/formancehq/earthly
IMPORT $core AS core
IMPORT ../../../.. AS stack
IMPORT ../../.. AS components

FROM core+base-image

sources:
    FROM core+builder-image
    WORKDIR /src
    COPY (stack+sources/out --LOCATION=libs/go-libs) libs/go-libs
    WORKDIR /src/components/operator/tools/utils
    COPY --dir cmd .
    COPY go.* main.go .
    SAVE ARTIFACT /src

compile:
    FROM core+builder-image
    COPY (+sources/*) /src
    WORKDIR /src/components/operator/tools/utils
	DO core+GO_COMPILE

build-image:
    FROM core+final-image
    ENTRYPOINT ["/usr/bin/operator-utils"]
    COPY (+compile/main) /usr/bin/operator-utils
    ARG REPOSITORY=ghcr.io
    ARG tag=latest
    DO core+SAVE_IMAGE --COMPONENT=operator-utils --TAG=$tag

lint:
    FROM core+builder-image
    COPY (+sources/*) /src
    COPY +tidy/go.* .
    WORKDIR /src/components/operator/tools/utils
    DO stack+GO_LINT
    SAVE ARTIFACT cmd AS LOCAL cmd

pre-commit:
    WAIT
        BUILD +tidy
    END
    BUILD +lint

tidy:
    FROM core+builder-image
    COPY (+sources/src) /src
    WORKDIR /src/components/operator/tools/utils
    DO stack+GO_TIDY

release:
    BUILD stack+goreleaser --path=components/operator/tools/utils