// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AuthTypeInfo auth type info
//
// swagger:model AuthTypeInfo
type AuthTypeInfo struct {

	// created
	// Example: 2022-05-04T18:31:12.889104898Z
	Created string `json:"created,omitempty"`
}

// Validate validates this auth type info
func (m *AuthTypeInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this auth type info based on context it is used
func (m *AuthTypeInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AuthTypeInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AuthTypeInfo) UnmarshalBinary(b []byte) error {
	var res AuthTypeInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
