// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// BankSlim Slim variant of Bank, a strict subset.
//
// swagger:model BankSlim
type BankSlim struct {

	// bic
	// Example: ESSESESSXXX
	Bic string `json:"bic,omitempty"`

	// id
	// Example: 5013c38e-8e01-4ad3-aff6-a57d51ec2158
	ID string `json:"id,omitempty"`

	// name
	// Example: SEB
	Name string `json:"name,omitempty"`
}

// Validate validates this bank slim
func (m *BankSlim) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this bank slim based on context it is used
func (m *BankSlim) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BankSlim) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BankSlim) UnmarshalBinary(b []byte) error {
	var res BankSlim
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
