// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TestbankBankTransactionCode testbank bank transaction code
//
// swagger:model testbank.BankTransactionCode
type TestbankBankTransactionCode struct {

	// domain
	Domain string `json:"domain,omitempty"`

	// family
	Family string `json:"family,omitempty"`

	// subfamily
	Subfamily string `json:"subfamily,omitempty"`
}

// Validate validates this testbank bank transaction code
func (m *TestbankBankTransactionCode) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this testbank bank transaction code based on context it is used
func (m *TestbankBankTransactionCode) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TestbankBankTransactionCode) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TestbankBankTransactionCode) UnmarshalBinary(b []byte) error {
	var res TestbankBankTransactionCode
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
