/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ConfigInfo } from "./configinfo";
import { Expose, Type } from "class-transformer";

/**
 * OK
 */
export class ConfigInfoResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => ConfigInfo)
    data: ConfigInfo;
}
