/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { TriggerOccurrence } from "./triggeroccurrence";
import { Expose, Type } from "class-transformer";

/**
 * List of triggers occurrences
 */
export class ListTriggersOccurrencesResponse extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: TriggerOccurrence })
  @Expose({ name: "data" })
  @Type(() => TriggerOccurrence)
  data: TriggerOccurrence[];
}
