/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { WebhooksErrorsEnum } from "./webhookserrorsenum";
import { Expose } from "class-transformer";

/**
 * Error
 */
export class WebhooksErrorResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "details" })
  details?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "errorCode" })
  errorCode: WebhooksErrorsEnum;

  @SpeakeasyMetadata()
  @Expose({ name: "errorMessage" })
  errorMessage: string;
}
