VERSION 0.8

IMPORT github.com/formancehq/earthly:tags/v0.14.0 AS core
IMPORT ../.. AS stack

FROM core+base-image

sources:
    COPY . /src
    WORKDIR src
    SAVE ARTIFACT /src

tidy:
    FROM core+builder-image
    COPY (+sources/*) /src
    WORKDIR /src
    DO --pass-args stack+GO_TIDY
    SAVE ARTIFACT go.* AS LOCAL ./

lint:
    FROM core+builder-image
    COPY (+sources/*) /src
    WORKDIR /src
    COPY --pass-args +tidy/go.* .
    DO --pass-args stack+GO_LINT
    SAVE ARTIFACT * AS LOCAL ./

pre-commit:
    WAIT
      BUILD --pass-args +tidy
    END
    BUILD --pass-args +lint