VERSION 0.8

ARG core=github.com/formancehq/earthly
IMPORT $core AS core
IMPORT ../.. AS stack

FROM core+base-image

sources:
    COPY . /src
    WORKDIR src
    SAVE ARTIFACT /src

tidy:
    FROM core+builder-image
    COPY (+sources/*) /src
    WORKDIR /src
    DO stack+GO_TIDY
    SAVE ARTIFACT go.* AS LOCAL ./

lint:
    FROM core+builder-image
    COPY (+sources/*) /src
    WORKDIR /src
    COPY +tidy/go.* .
    DO stack+GO_LINT
    SAVE ARTIFACT * AS LOCAL ./

pre-commit:
    WAIT
      BUILD +tidy
    END
    BUILD +lint