VERSION 0.8

IMPORT github.com/formancehq/earthly:tags/v0.14.0 AS core
IMPORT ../.. AS stack

FROM core+base-image

sources:
    COPY . /src
    WORKDIR src
    SAVE ARTIFACT /src

tidy:
    FROM core+builder-image
    COPY (+sources/*) /src
    WORKDIR /src
    DO --pass-args stack+GO_TIDY
    SAVE ARTIFACT go.* AS LOCAL ./

lint:
    FROM core+builder-image
    COPY (+sources/*) /src
    WORKDIR /src
    COPY --pass-args +tidy/go.* .
    DO --pass-args stack+GO_LINT
    SAVE ARTIFACT * AS LOCAL ./

generate:
    FROM core+builder-image
    RUN apk update && apk add openjdk11
    DO --pass-args core+GO_INSTALL --package=go.uber.org/mock/mockgen@latest
    COPY (+sources/*) /src
    WORKDIR /src
    DO --pass-args core+GO_GENERATE
    FOR dir IN $(ls -d */)
        SAVE ARTIFACT $dir AS LOCAL ./
    END

pre-commit:
    WAIT
      BUILD --pass-args +tidy
    END
    BUILD --pass-args +lint