VERSION 0.8

IMPORT github.com/formancehq/earthly:feat/monorepo AS core
IMPORT .. AS stack

deploy:
    FROM core+base-image
    ARG --required components
    BUILD --pass-args ./$components+deploy

deploy-staging:
    FROM core+base-image
    ARG --required components
    BUILD --pass-args ./$components+deploy-staging

run:
    LOCALLY
    ARG --required TARGET
    BUILD ./fctl+$TARGET
    BUILD ./ledger+$TARGET
    BUILD ./operator+$TARGET
    BUILD ./payments+$TARGET