/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class CreateSecretResponse {
    
    public String contentType;

    public CreateSecretResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Created secret
     */
    
    public org.openapis.openapi.models.shared.CreateSecretResponse createSecretResponse;

    public CreateSecretResponse withCreateSecretResponse(org.openapis.openapi.models.shared.CreateSecretResponse createSecretResponse) {
        this.createSecretResponse = createSecretResponse;
        return this;
    }
    
    
    public Integer statusCode;

    public CreateSecretResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public CreateSecretResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public CreateSecretResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
