/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetBalanceResponse {
    
    public String contentType;

    public GetBalanceResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Balance summary
     */
    
    public org.openapis.openapi.models.shared.GetBalanceResponse getBalanceResponse;

    public GetBalanceResponse withGetBalanceResponse(org.openapis.openapi.models.shared.GetBalanceResponse getBalanceResponse) {
        this.getBalanceResponse = getBalanceResponse;
        return this;
    }
    
    
    public Integer statusCode;

    public GetBalanceResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetBalanceResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Error
     */
    
    public org.openapis.openapi.models.shared.WalletsErrorResponse walletsErrorResponse;

    public GetBalanceResponse withWalletsErrorResponse(org.openapis.openapi.models.shared.WalletsErrorResponse walletsErrorResponse) {
        this.walletsErrorResponse = walletsErrorResponse;
        return this;
    }
    
    public GetBalanceResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
