/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class PaymentslistAccountsResponse {
    /**
     * OK
     */
    
    public org.openapis.openapi.models.shared.AccountsCursor accountsCursor;

    public PaymentslistAccountsResponse withAccountsCursor(org.openapis.openapi.models.shared.AccountsCursor accountsCursor) {
        this.accountsCursor = accountsCursor;
        return this;
    }
    
    
    public String contentType;

    public PaymentslistAccountsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public PaymentslistAccountsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public PaymentslistAccountsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public PaymentslistAccountsResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
