// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
)

// ReconciliationErrorResponse - Error response
type ReconciliationErrorResponse struct {
	Details      *string `json:"details,omitempty"`
	ErrorCode    string  `json:"errorCode"`
	ErrorMessage string  `json:"errorMessage"`
}

var _ error = &ReconciliationErrorResponse{}

func (e *ReconciliationErrorResponse) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
