/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

public class CreateWalletRequest {
    /**
     * Custom metadata to attach to this wallet.
     */
    @JsonProperty("metadata")
    public java.util.Map<String, String> metadata;

    public CreateWalletRequest withMetadata(java.util.Map<String, String> metadata) {
        this.metadata = metadata;
        return this;
    }
    
    @JsonProperty("name")
    public String name;

    public CreateWalletRequest withName(String name) {
        this.name = name;
        return this;
    }
    
    public CreateWalletRequest(@JsonProperty("metadata") java.util.Map<String, String> metadata, @JsonProperty("name") String name) {
        this.metadata = metadata;
        this.name = name;
  }
}
