/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.formance.formance_sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.formance.formance_sdk.utils.SpeakeasyMetadata;

public class GetBalanceRequest {
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=balanceName")
    public String balanceName;

    public GetBalanceRequest withBalanceName(String balanceName) {
        this.balanceName = balanceName;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=id")
    public String id;

    public GetBalanceRequest withId(String id) {
        this.id = id;
        return this;
    }
    
    public GetBalanceRequest(@JsonProperty("balanceName") String balanceName, @JsonProperty("id") String id) {
        this.balanceName = balanceName;
        this.id = id;
  }
}
