/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.formance.formance_sdk.models.operations;



/**
 * ListAccountsMetadata - Filter accounts by metadata key value pairs. Nested objects can be used as seen in the example below.
 */

public class ListAccountsMetadata {
    public ListAccountsMetadata(){}
}
