<?php
/**
 * GetWalletSummaryResponse
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Formance
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Formance Stack API
 *
 * Open, modular foundation for unique payments flows  # Introduction This API is documented in **OpenAPI format**.  # Authentication Formance Stack offers one forms of authentication:   - OAuth2 OAuth2 - an open protocol to allow secure authorization in a simple and standard method from web, mobile and desktop applications. <SecurityDefinitions />
 *
 * The version of the OpenAPI document: develop
 * Contact: support@formance.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Formance\Model;

use \ArrayAccess;
use \Formance\ObjectSerializer;

/**
 * GetWalletSummaryResponse Class Doc Comment
 *
 * @category Class
 * @package  Formance
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetWalletSummaryResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'GetWalletSummaryResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'balances' => '\Formance\Model\BalanceWithAssets[]',
        'available_funds' => 'array<string,int>',
        'expired_funds' => 'array<string,int>',
        'expirable_funds' => 'array<string,int>',
        'hold_funds' => 'array<string,int>'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'balances' => null,
        'available_funds' => null,
        'expired_funds' => null,
        'expirable_funds' => null,
        'hold_funds' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'balances' => false,
		'available_funds' => false,
		'expired_funds' => false,
		'expirable_funds' => false,
		'hold_funds' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'balances' => 'balances',
        'available_funds' => 'availableFunds',
        'expired_funds' => 'expiredFunds',
        'expirable_funds' => 'expirableFunds',
        'hold_funds' => 'holdFunds'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'balances' => 'setBalances',
        'available_funds' => 'setAvailableFunds',
        'expired_funds' => 'setExpiredFunds',
        'expirable_funds' => 'setExpirableFunds',
        'hold_funds' => 'setHoldFunds'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'balances' => 'getBalances',
        'available_funds' => 'getAvailableFunds',
        'expired_funds' => 'getExpiredFunds',
        'expirable_funds' => 'getExpirableFunds',
        'hold_funds' => 'getHoldFunds'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('balances', $data ?? [], null);
        $this->setIfExists('available_funds', $data ?? [], null);
        $this->setIfExists('expired_funds', $data ?? [], null);
        $this->setIfExists('expirable_funds', $data ?? [], null);
        $this->setIfExists('hold_funds', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['balances'] === null) {
            $invalidProperties[] = "'balances' can't be null";
        }
        if ($this->container['available_funds'] === null) {
            $invalidProperties[] = "'available_funds' can't be null";
        }
        if ($this->container['expired_funds'] === null) {
            $invalidProperties[] = "'expired_funds' can't be null";
        }
        if ($this->container['expirable_funds'] === null) {
            $invalidProperties[] = "'expirable_funds' can't be null";
        }
        if ($this->container['hold_funds'] === null) {
            $invalidProperties[] = "'hold_funds' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets balances
     *
     * @return \Formance\Model\BalanceWithAssets[]
     */
    public function getBalances()
    {
        return $this->container['balances'];
    }

    /**
     * Sets balances
     *
     * @param \Formance\Model\BalanceWithAssets[] $balances balances
     *
     * @return self
     */
    public function setBalances($balances)
    {
        if (is_null($balances)) {
            throw new \InvalidArgumentException('non-nullable balances cannot be null');
        }
        $this->container['balances'] = $balances;

        return $this;
    }

    /**
     * Gets available_funds
     *
     * @return array<string,int>
     */
    public function getAvailableFunds()
    {
        return $this->container['available_funds'];
    }

    /**
     * Sets available_funds
     *
     * @param array<string,int> $available_funds available_funds
     *
     * @return self
     */
    public function setAvailableFunds($available_funds)
    {
        if (is_null($available_funds)) {
            throw new \InvalidArgumentException('non-nullable available_funds cannot be null');
        }
        $this->container['available_funds'] = $available_funds;

        return $this;
    }

    /**
     * Gets expired_funds
     *
     * @return array<string,int>
     */
    public function getExpiredFunds()
    {
        return $this->container['expired_funds'];
    }

    /**
     * Sets expired_funds
     *
     * @param array<string,int> $expired_funds expired_funds
     *
     * @return self
     */
    public function setExpiredFunds($expired_funds)
    {
        if (is_null($expired_funds)) {
            throw new \InvalidArgumentException('non-nullable expired_funds cannot be null');
        }
        $this->container['expired_funds'] = $expired_funds;

        return $this;
    }

    /**
     * Gets expirable_funds
     *
     * @return array<string,int>
     */
    public function getExpirableFunds()
    {
        return $this->container['expirable_funds'];
    }

    /**
     * Sets expirable_funds
     *
     * @param array<string,int> $expirable_funds expirable_funds
     *
     * @return self
     */
    public function setExpirableFunds($expirable_funds)
    {
        if (is_null($expirable_funds)) {
            throw new \InvalidArgumentException('non-nullable expirable_funds cannot be null');
        }
        $this->container['expirable_funds'] = $expirable_funds;

        return $this;
    }

    /**
     * Gets hold_funds
     *
     * @return array<string,int>
     */
    public function getHoldFunds()
    {
        return $this->container['hold_funds'];
    }

    /**
     * Sets hold_funds
     *
     * @param array<string,int> $hold_funds hold_funds
     *
     * @return self
     */
    public function setHoldFunds($hold_funds)
    {
        if (is_null($hold_funds)) {
            throw new \InvalidArgumentException('non-nullable hold_funds cannot be null');
        }
        $this->container['hold_funds'] = $hold_funds;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


