VERSION 0.8

IMPORT github.com/formancehq/earthly:feat/monorepo AS core

sources:
    FROM core+base-image
    WORKDIR /src
    COPY --dir core .
    SAVE ARTIFACT /src

helm-validate:
    FROM core+helm-base
    WORKDIR /src
    COPY (+sources/*) .
    FOR chart IN $(ls -d */)
        WORKDIR /src/$chart
        RUN helm lint .
    END
    SAVE ARTIFACT /src/* AS LOCAL .