// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/formancehq/formance-sdk-go/pkg/utils"
	"time"
)

type Ledger struct {
	AddedAt time.Time `json:"addedAt"`
	Bucket  string    `json:"bucket"`
	Name    string    `json:"name"`
}

func (l Ledger) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *Ledger) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *Ledger) GetAddedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.AddedAt
}

func (o *Ledger) GetBucket() string {
	if o == nil {
		return ""
	}
	return o.Bucket
}

func (o *Ledger) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}
