VERSION --arg-scope-and-set --pass-args --use-function-keyword 0.7

ARG core=github.com/formancehq/earthly:v0.10.0
IMPORT $core AS core
IMPORT .. AS stack

deploy:
    FROM core+base-image
    ARG --required components
    BUILD --pass-args ./$components+deploy