VERSION 0.8

ARG core=github.com/formancehq/earthly

IMPORT $core AS core
IMPORT .. AS stack

deploy:
    FROM core+base-image
    ARG --required components
    BUILD --pass-args ./$components+deploy

deploy-staging:
    FROM core+base-image
    ARG --required components
    BUILD --pass-args ./$components+deploy-staging