VERSION 0.8

IMPORT github.com/formancehq/earthly:tags/v0.14.0 AS core
IMPORT .. AS stack

run:
  LOCALLY
  ARG --required TARGET
  BUILD ./core+$TARGET
  BUILD ./events+$TARGET
  BUILD ./go-libs+$TARGET
