VERSION 0.8

IMPORT github.com/formancehq/earthly:baaa0352c718937be6f9c40fe40879642bbd6132 AS core
IMPORT .. AS stack

run:
  LOCALLY
  ARG --required TARGET
  BUILD ./core+$TARGET
  BUILD ./events+$TARGET
  BUILD ./go-libs+$TARGET
