/*
Formance Stack API

Open, modular foundation for unique payments flows  # Introduction This API is documented in **OpenAPI format**.  # Authentication Formance Stack offers one forms of authentication:   - OAuth2 OAuth2 - an open protocol to allow secure authorization in a simple and standard method from web, mobile and desktop applications. <SecurityDefinitions /> 

API version: develop
Contact: support@formance.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package formance

import (
	"encoding/json"
	"time"
)

// checks if the WorkflowInstanceHistory type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowInstanceHistory{}

// WorkflowInstanceHistory struct for WorkflowInstanceHistory
type WorkflowInstanceHistory struct {
	Name string `json:"name"`
	Input Stage `json:"input"`
	Error *string `json:"error,omitempty"`
	Terminated bool `json:"terminated"`
	StartedAt time.Time `json:"startedAt"`
	TerminatedAt *time.Time `json:"terminatedAt,omitempty"`
}

// NewWorkflowInstanceHistory instantiates a new WorkflowInstanceHistory object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowInstanceHistory(name string, input Stage, terminated bool, startedAt time.Time) *WorkflowInstanceHistory {
	this := WorkflowInstanceHistory{}
	this.Name = name
	this.Input = input
	this.Terminated = terminated
	this.StartedAt = startedAt
	return &this
}

// NewWorkflowInstanceHistoryWithDefaults instantiates a new WorkflowInstanceHistory object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowInstanceHistoryWithDefaults() *WorkflowInstanceHistory {
	this := WorkflowInstanceHistory{}
	return &this
}

// GetName returns the Name field value
func (o *WorkflowInstanceHistory) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *WorkflowInstanceHistory) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *WorkflowInstanceHistory) SetName(v string) {
	o.Name = v
}

// GetInput returns the Input field value
func (o *WorkflowInstanceHistory) GetInput() Stage {
	if o == nil {
		var ret Stage
		return ret
	}

	return o.Input
}

// GetInputOk returns a tuple with the Input field value
// and a boolean to check if the value has been set.
func (o *WorkflowInstanceHistory) GetInputOk() (*Stage, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Input, true
}

// SetInput sets field value
func (o *WorkflowInstanceHistory) SetInput(v Stage) {
	o.Input = v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *WorkflowInstanceHistory) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowInstanceHistory) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *WorkflowInstanceHistory) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *WorkflowInstanceHistory) SetError(v string) {
	o.Error = &v
}

// GetTerminated returns the Terminated field value
func (o *WorkflowInstanceHistory) GetTerminated() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Terminated
}

// GetTerminatedOk returns a tuple with the Terminated field value
// and a boolean to check if the value has been set.
func (o *WorkflowInstanceHistory) GetTerminatedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Terminated, true
}

// SetTerminated sets field value
func (o *WorkflowInstanceHistory) SetTerminated(v bool) {
	o.Terminated = v
}

// GetStartedAt returns the StartedAt field value
func (o *WorkflowInstanceHistory) GetStartedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.StartedAt
}

// GetStartedAtOk returns a tuple with the StartedAt field value
// and a boolean to check if the value has been set.
func (o *WorkflowInstanceHistory) GetStartedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartedAt, true
}

// SetStartedAt sets field value
func (o *WorkflowInstanceHistory) SetStartedAt(v time.Time) {
	o.StartedAt = v
}

// GetTerminatedAt returns the TerminatedAt field value if set, zero value otherwise.
func (o *WorkflowInstanceHistory) GetTerminatedAt() time.Time {
	if o == nil || IsNil(o.TerminatedAt) {
		var ret time.Time
		return ret
	}
	return *o.TerminatedAt
}

// GetTerminatedAtOk returns a tuple with the TerminatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowInstanceHistory) GetTerminatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.TerminatedAt) {
		return nil, false
	}
	return o.TerminatedAt, true
}

// HasTerminatedAt returns a boolean if a field has been set.
func (o *WorkflowInstanceHistory) HasTerminatedAt() bool {
	if o != nil && !IsNil(o.TerminatedAt) {
		return true
	}

	return false
}

// SetTerminatedAt gets a reference to the given time.Time and assigns it to the TerminatedAt field.
func (o *WorkflowInstanceHistory) SetTerminatedAt(v time.Time) {
	o.TerminatedAt = &v
}

func (o WorkflowInstanceHistory) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowInstanceHistory) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["input"] = o.Input
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	toSerialize["terminated"] = o.Terminated
	toSerialize["startedAt"] = o.StartedAt
	if !IsNil(o.TerminatedAt) {
		toSerialize["terminatedAt"] = o.TerminatedAt
	}
	return toSerialize, nil
}

type NullableWorkflowInstanceHistory struct {
	value *WorkflowInstanceHistory
	isSet bool
}

func (v NullableWorkflowInstanceHistory) Get() *WorkflowInstanceHistory {
	return v.value
}

func (v *NullableWorkflowInstanceHistory) Set(val *WorkflowInstanceHistory) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowInstanceHistory) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowInstanceHistory) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowInstanceHistory(val *WorkflowInstanceHistory) *NullableWorkflowInstanceHistory {
	return &NullableWorkflowInstanceHistory{value: val, isSet: true}
}

func (v NullableWorkflowInstanceHistory) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowInstanceHistory) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


