/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.formance.formance_sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;


public class ActivityGetWalletOutput {
    @JsonProperty("data")
    public WalletWithBalances data;

    public ActivityGetWalletOutput withData(WalletWithBalances data) {
        this.data = data;
        return this;
    }
    
    public ActivityGetWalletOutput(@JsonProperty("data") WalletWithBalances data) {
        this.data = data;
  }
}
