/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.formance.formance_sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * AttemptResponse - OK
 */
public class AttemptResponse {
    @JsonProperty("data")
    public Attempt data;

    public AttemptResponse withData(Attempt data) {
        this.data = data;
        return this;
    }
    
    public AttemptResponse(@JsonProperty("data") Attempt data) {
        this.data = data;
  }
}
