/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.formance.formance_sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

public class ConnectorResponseData {
    @JsonProperty("connectorID")
    public String connectorID;

    public ConnectorResponseData withConnectorID(String connectorID) {
        this.connectorID = connectorID;
        return this;
    }
    
    public ConnectorResponseData(@JsonProperty("connectorID") String connectorID) {
        this.connectorID = connectorID;
  }
}
