clients:
  - id: control
    secrets:
      - mysupersecret
    redirectUris:
      - http://localhost:3000/auth/login
      - https://oauth.pstmn.io/v1/callback
    name: control
    postLogoutRedirectUris:
      - http://localhost:3000/auth/logout