VERSION 0.8

IMPORT github.com/formancehq/earthly:tags/v0.12.0 AS core
IMPORT .. AS stack
IMPORT ../components/operator AS operator

sources:
  FROM core+base-image
  WORKDIR /src
  COPY --dir regions regions
  SAVE ARTIFACT /src

helm-validate:
  FROM core+helm-base
  WORKDIR /src
  COPY (stack+sources/out --LOCATION=ee/agent/helm) /src/ee/agent/helm
  COPY (operator+helm-update/*) /src/components/operator/helm/

  WORKDIR /src/helm
  COPY . .
  FOR chart IN $(ls -d */)
    WORKDIR /src/helm
    COPY ./$chart $chart
    WORKDIR /src/helm/$chart
    RUN helm dependency update
    DO --pass-args core+HELM_VALIDATE
  END
  SAVE ARTIFACT /src/helm/* AS LOCAL .

pre-commit:
  BUILD --pass-args ./regions+helm-validate

publish:
  BUILD --pass-args ./regions+helm-publish