VERSION --arg-scope-and-set --pass-args 0.7

ARG core=github.com/formancehq/earthly:v0.5.2
IMPORT $core AS core

sources:
  FROM core+base-image
  WORKDIR /src
  COPY --dir regions regions
  SAVE ARTIFACT /src
