VERSION 0.8

IMPORT github.com/formancehq/earthly:tags/v0.15.0 AS core

FROM core+base-image

GO_LINT:
    FUNCTION
    COPY (+sources/out --LOCATION=.golangci.yml) .golangci.yml
    ARG GOPROXY
    RUN --mount=type=cache,id=gomod,target=${GOPATH}/pkg/mod \
        --mount=type=cache,id=gobuild,target=/root/.cache/go-build \
        --mount=type=cache,id=golangci,target=/root/.cache/golangci-lint \
        golangci-lint run --fix ./...

GO_TIDY:
    FUNCTION
    ARG GOPROXY
    RUN --mount=type=cache,id=gomod,target=${GOPATH}/pkg/mod \
        --mount=type=cache,id=gobuild,target=/root/.cache/go-build \
        go mod tidy
    SAVE ARTIFACT go.* AS LOCAL .

go-sources:
    COPY events.go go.* base.yaml /src/
    COPY --dir services /src/
    WORKDIR /src
    SAVE ARTIFACT /src

tidy:
    FROM core+builder-image
    COPY (+go-sources/*) /src
    WORKDIR /src
    DO --pass-args +GO_TIDY
    SAVE ARTIFACT go.* AS LOCAL ./

lint:
    FROM core+builder-image
    COPY (+go-sources/*) /src
    WORKDIR /src
    COPY --pass-args +tidy/go.* .
    DO --pass-args +GO_LINT
    SAVE ARTIFACT * AS LOCAL ./

generate:
    RUN apk add nodejs npm
    WORKDIR /src
    COPY package* .
    RUN npm install
    RUN mkdir generated
    COPY index.js base.yaml .
    COPY --dir services .
    RUN node index.js
    SAVE ARTIFACT generated AS LOCAL ./generated

pre-commit:
    WAIT
      BUILD --pass-args +tidy
    END
    BUILD --pass-args +generate
