VERSION 0.8
PROJECT FormanceHQ/fctl

IMPORT github.com/formancehq/earthly:feat/monorepo AS core

FROM core+base-image

build-image:
    RUN echo "not implemented"

deploy:
    RUN echo "not implemented"

tests:
    RUN echo "not implemented"

deploy-staging:
    RUN echo "not implemented"

sources:
    WORKDIR /src
    DO core+INCLURE_SDK_GO --LOCATION /src/libs/sdks/stacks
    COPY (+generate-membership-client/*) /src/libs/sdks/membership
    COPY go.* .
    COPY --dir cmd pkg .
    COPY main.go .
    SAVE ARTIFACT /src

lint:
    FROM core+builder-image
    WORKDIR /src
    COPY --dir (+tidy/src/*) /src
    DO --pass-args core+GO_LINT
    SAVE ARTIFACT cmd AS LOCAL cmd
    SAVE ARTIFACT pkg AS LOCAL pkg
    SAVE ARTIFACT main.go AS LOCAL main.go

pre-commit:
    WAIT
        BUILD --pass-args +tidy
    END
    BUILD --pass-args +lint
    BUILD --pass-args +completions

completions:
    FROM core+builder-image
    WORKDIR /src
    COPY --dir (+sources/src/*) /src
    RUN mkdir -p ./completions
    RUN go run main.go completion bash > "./completions/fctl.bash"
    RUN go run main.go completion zsh > "./completions/fctl.zsh"
    RUN go run main.go completion fish > "./completions/fctl.fish"
    SAVE ARTIFACT ./completions AS LOCAL completions

openapi:
    RUN echo "not implemented"

tidy:
    FROM core+builder-image
    WORKDIR /src
    COPY --dir (+sources/*) /src
    DO --pass-args core+GO_TIDY
    SAVE ARTIFACT /src AS LOCAL ./

membership-openapi:
    FROM core+base-image
    WORKDIR /src
    COPY membership-swagger.yaml openapi.yaml
    SAVE ARTIFACT openapi.yaml

generate-membership-client:
    FROM openapitools/openapi-generator-cli:v6.6.0
    WORKDIR /src
    COPY (+membership-openapi/openapi.yaml) .
    RUN docker-entrypoint.sh generate \
        -i ./openapi.yaml \
        -g go \
        -o ./ \
        --git-user-id=formancehq \
        --git-repo-id=fctl \
        -p packageVersion=latest \
        -p isGoSubmodule=true \
        -p packageName=membershipclient
    RUN rm -rf ./test ./openapi.yaml
    SAVE ARTIFACT /src

release:
    FROM core+builder-image
    ARG mode=local
    COPY --dir . /src
    DO core+GORELEASER --mode=$mode