// Code generated by go-swagger; DO NOT EDIT.

package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/formancehq/payments/cmd/connectors/internal/connectors/atlar/models"
)

// NewPutV1AccountsIDParams creates a new PutV1AccountsIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutV1AccountsIDParams() *PutV1AccountsIDParams {
	return &PutV1AccountsIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutV1AccountsIDParamsWithTimeout creates a new PutV1AccountsIDParams object
// with the ability to set a timeout on a request.
func NewPutV1AccountsIDParamsWithTimeout(timeout time.Duration) *PutV1AccountsIDParams {
	return &PutV1AccountsIDParams{
		timeout: timeout,
	}
}

// NewPutV1AccountsIDParamsWithContext creates a new PutV1AccountsIDParams object
// with the ability to set a context for a request.
func NewPutV1AccountsIDParamsWithContext(ctx context.Context) *PutV1AccountsIDParams {
	return &PutV1AccountsIDParams{
		Context: ctx,
	}
}

// NewPutV1AccountsIDParamsWithHTTPClient creates a new PutV1AccountsIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutV1AccountsIDParamsWithHTTPClient(client *http.Client) *PutV1AccountsIDParams {
	return &PutV1AccountsIDParams{
		HTTPClient: client,
	}
}

/*
PutV1AccountsIDParams contains all the parameters to send to the API endpoint

	for the put v1 accounts ID operation.

	Typically these are written to a http.Request.
*/
type PutV1AccountsIDParams struct {

	/* Account.

	   Account
	*/
	Account *models.UpdateAccountRequest

	/* ID.

	   Account ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put v1 accounts ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutV1AccountsIDParams) WithDefaults() *PutV1AccountsIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put v1 accounts ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutV1AccountsIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put v1 accounts ID params
func (o *PutV1AccountsIDParams) WithTimeout(timeout time.Duration) *PutV1AccountsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put v1 accounts ID params
func (o *PutV1AccountsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put v1 accounts ID params
func (o *PutV1AccountsIDParams) WithContext(ctx context.Context) *PutV1AccountsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put v1 accounts ID params
func (o *PutV1AccountsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put v1 accounts ID params
func (o *PutV1AccountsIDParams) WithHTTPClient(client *http.Client) *PutV1AccountsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put v1 accounts ID params
func (o *PutV1AccountsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccount adds the account to the put v1 accounts ID params
func (o *PutV1AccountsIDParams) WithAccount(account *models.UpdateAccountRequest) *PutV1AccountsIDParams {
	o.SetAccount(account)
	return o
}

// SetAccount adds the account to the put v1 accounts ID params
func (o *PutV1AccountsIDParams) SetAccount(account *models.UpdateAccountRequest) {
	o.Account = account
}

// WithID adds the id to the put v1 accounts ID params
func (o *PutV1AccountsIDParams) WithID(id string) *PutV1AccountsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put v1 accounts ID params
func (o *PutV1AccountsIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PutV1AccountsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Account != nil {
		if err := r.SetBodyParam(o.Account); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
