VERSION 0.8

ARG core=github.com/formancehq/earthly

IMPORT $core AS core
IMPORT ../.. AS stack
IMPORT .. AS ee

FROM core+base-image

sources:
    WORKDIR src
    DO stack+INCLUDE_GO_LIBS --LOCATION libs/go-libs
    WORKDIR /src/ee/gateway
    COPY go.* .
    COPY --dir internal .
    COPY --dir pkg .
    COPY main.go Caddyfile .
    SAVE ARTIFACT /src

compile:
    FROM core+builder-image
    COPY (+sources/*) /src
    WORKDIR /src/ee/gateway
    ARG VERSION=latest
    DO core+GO_COMPILE --VERSION=$VERSION

build-image:
    FROM core+final-image
    ENTRYPOINT ["/usr/bin/caddy"]
    CMD ["run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]
    COPY Caddyfile /etc/caddy/Caddyfile
    COPY (+compile/main) /usr/bin/caddy
    ARG REPOSITORY=ghcr.io
    ARG tag=latest
    DO core+SAVE_IMAGE --COMPONENT=gateway --REPOSITORY=${REPOSITORY} --TAG=$tag

deploy:
    COPY (+sources/*) /src
    LET tag=$(tar cf - /src | sha1sum | awk '{print $1}')
    WAIT
        BUILD +build-image --tag=$tag
    END
    FROM core+vcluster-deployer-image
    RUN kubectl patch Versions.formance.com default -p "{\"spec\":{\"gateway\": \"${tag}\"}}" --type=merge

deploy-staging:
    BUILD stack+deployer-module --MODULE=gateway
lint:
    FROM core+builder-image
    COPY (+sources/*) /src
    COPY +tidy/go.* .
    WORKDIR /src/ee/gateway
    DO stack+GO_LINT
    SAVE ARTIFACT internal AS LOCAL internal
    SAVE ARTIFACT pkg AS LOCAL pkg
    SAVE ARTIFACT main.go AS LOCAL main.go

tests:
    FROM core+builder-image
    COPY (+sources/*) /src
    WORKDIR /src/ee/gateway
    DO core+GO_TESTS

pre-commit:
    WAIT
      BUILD +tidy
    END
    BUILD +lint

openapi:
    RUN echo "not implemented"

tidy:
    FROM core+builder-image
    COPY (+sources/src) /src
    WORKDIR /src/ee/gateway
    DO stack+GO_TIDY

release:
    BUILD stack+goreleaser --path=ee/gateway