VERSION 0.8

IMPORT github.com/formancehq/earthly:feat/monorepo AS core

FROM core+base-image

sources:
    COPY . /src
    WORKDIR src
    SAVE ARTIFACT /src

tidy:
    FROM core+builder-image
    COPY (+sources/*) /src
    WORKDIR /src
    DO --pass-args core+GO_TIDY
    SAVE ARTIFACT go.* AS LOCAL ./

lint:
    FROM core+builder-image
    COPY (+sources/*) /src
    WORKDIR /src
    COPY --pass-args +tidy/go.* .
    DO --pass-args core+GO_LINT
    SAVE ARTIFACT accounts AS LOCAL accounts
    SAVE ARTIFACT assets AS LOCAL assets

pre-commit:
    WAIT
      BUILD --pass-args +tidy
    END
    BUILD --pass-args +lint